"""
services/sbom-service/app/domain/entities.py

Pure domain entities for the SBOM service.

Rules enforced here:
- NO imports from infrastructure/, application/, or interface/.
- NO framework imports (no FastAPI, SQLAlchemy, asyncpg, etc.).
- All fields are typed; optional fields have a default.
- Frozen dataclasses guarantee value-object immutability.
- Business invariants are enforced in __post_init__ or classmethods.
"""

from __future__ import annotations

import hashlib
import json
import re
import uuid
from dataclasses import dataclass
from datetime import UTC, datetime
from enum import Enum
from typing import Any

# ---------------------------------------------------------------------------
# Enumerations
# ---------------------------------------------------------------------------


class VerificationStatus(str, Enum):
    """Cosign/Sigstore signature verification lifecycle state."""

    PENDING = "pending"
    """Verification has not yet started or is enqueued."""

    VERIFIED = "verified"
    """Verification completed successfully; signature is trusted."""

    FAILED = "failed"
    """Verification completed but the signature is invalid or absent."""


class SbomSource(str, Enum):
    """Provenance of the submitted SBOM document."""

    SYFT = "syft"
    """Generated by the Syft CLI during CI or admission control."""

    EXTERNAL = "external"
    """Submitted by an external producer; signature bundle is mandatory."""


class BindingStatus(str, Enum):
    """Quality of a PURL-to-runtime component binding."""

    RESOLVED = "resolved"
    """PURL is unambiguously matched to a runtime component."""

    AMBIGUOUS = "ambiguous"
    """Multiple PURLs match; binding is uncertain."""

    MISSING = "missing"
    """No SBOM binding could be established for this component."""


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

_DIGEST_RE = re.compile(r"^sha256:[0-9a-f]{64}$")
"""Pattern for validating sha256:<64 hex chars> digest fields."""

_CYCLONEDX_FORMAT_FIELD = "bomFormat"
"""Required top-level field in a CycloneDX JSON document."""

_CYCLONEDX_COMPONENTS_FIELD = "components"
"""Field name for the component list in a CycloneDX document."""


# ---------------------------------------------------------------------------
# Value objects
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class ImageDigest:
    """Immutable value object wrapping a validated container image digest.

    Attributes:
        value: The raw digest string, e.g. ``sha256:<64 hex chars>``.
    """

    value: str
    """Raw digest string in sha256:<64 hex chars> format."""

    def __post_init__(self) -> None:
        """Validate the digest format on construction.

        Raises:
            ValueError: If the digest does not match the required format.
        """
        if not _DIGEST_RE.match(self.value):
            raise ValueError(
                f"ImageDigest must match sha256:<64 hex chars>, got {self.value!r}"
            )

    def __str__(self) -> str:
        """Return the raw digest string.

        Returns:
            The raw digest string.
        """
        return self.value


@dataclass(frozen=True)
class SbomDigest:
    """Immutable value object wrapping a validated SBOM document digest.

    Attributes:
        value: The raw digest string, e.g. ``sha256:<64 hex chars>``.
    """

    value: str
    """Raw digest string in sha256:<64 hex chars> format."""

    def __post_init__(self) -> None:
        """Validate the digest format on construction.

        Raises:
            ValueError: If the digest does not match the required format.
        """
        if not _DIGEST_RE.match(self.value):
            raise ValueError(
                f"SbomDigest must match sha256:<64 hex chars>, got {self.value!r}"
            )

    def __str__(self) -> str:
        """Return the raw digest string.

        Returns:
            The raw digest string.
        """
        return self.value

    @classmethod
    def compute(cls, cyclonedx_document: dict[str, Any]) -> SbomDigest:
        """Compute the canonical sha256 digest of a CycloneDX document.

        Uses JSON with sorted keys and no extra whitespace to ensure
        deterministic digests regardless of input serialization order.

        Args:
            cyclonedx_document: The CycloneDX document as a parsed dict.

        Returns:
            The SbomDigest of the canonicalized document.
        """
        canonical_bytes = json.dumps(
            cyclonedx_document, sort_keys=True, separators=(",", ":")
        ).encode("utf-8")
        hex_digest = hashlib.sha256(canonical_bytes).hexdigest()
        return cls(value=f"sha256:{hex_digest}")


@dataclass(frozen=True)
class Purl:
    """Immutable value object for a Package URL (PURL).

    Attributes:
        value: The raw PURL string; 1..2048 characters.
    """

    value: str
    """Raw PURL string; 1..2048 characters."""

    def __post_init__(self) -> None:
        """Validate basic PURL constraints.

        Raises:
            ValueError: If the PURL is empty or exceeds 2048 characters.
        """
        if not self.value:
            raise ValueError("Purl value must not be empty")
        if len(self.value) > 2048:
            raise ValueError(
                f"Purl value must be at most 2048 characters, got {len(self.value)}"
            )

    def __str__(self) -> str:
        """Return the raw PURL string.

        Returns:
            The raw PURL string.
        """
        return self.value


# ---------------------------------------------------------------------------
# Domain entities
# ---------------------------------------------------------------------------


@dataclass
class Component:
    """A single software component from a CycloneDX SBOM.

    Represents one entry in the ``components`` array of a CycloneDX document,
    after normalization into the PHANTOM domain model.

    Attributes:
        component_id: Immutable UUID for this component record.
        sbom_id: UUID of the parent SBOM this component belongs to.
        purl: Package URL uniquely identifying this component version.
        name: Human-readable component name from the SBOM.
        version: Component version string; empty string if absent.
        component_type: CycloneDX component type (e.g. ``"library"``).
        binding_status: Quality of the runtime-to-SBOM PURL binding.
        binding_confidence: Confidence score for the binding [0.0, 1.0].
        created_at: UTC timestamp when this component record was created.
    """

    component_id: uuid.UUID
    """Immutable UUID assigned at ingestion time."""

    sbom_id: uuid.UUID
    """UUID of the parent SBOM this component belongs to."""

    purl: Purl
    """Package URL uniquely identifying this component version."""

    name: str
    """Human-readable component name from the SBOM."""

    version: str
    """Component version string; empty string if absent in the SBOM."""

    component_type: str
    """CycloneDX component type, e.g. 'library', 'framework', 'application'."""

    binding_status: BindingStatus
    """Quality of the runtime PURL-to-SBOM binding."""

    binding_confidence: float
    """Confidence score for the binding; range [0.0, 1.0]."""

    created_at: datetime
    """UTC timestamp when this component record was created."""

    def __post_init__(self) -> None:
        """Enforce Component invariants.

        Raises:
            ValueError: If name is empty, binding_confidence is out of range,
                or created_at is not timezone-aware.
        """
        if not self.name:
            raise ValueError("Component.name must not be empty")
        if not (0.0 <= self.binding_confidence <= 1.0):
            raise ValueError(
                f"Component.binding_confidence must be in [0, 1], "
                f"got {self.binding_confidence}"
            )
        if self.created_at.tzinfo is None:
            raise ValueError("Component.created_at must be timezone-aware")

    @classmethod
    def from_cyclonedx_component(
        cls,
        raw: dict[str, Any],
        sbom_id: uuid.UUID,
    ) -> Component:
        """Create a Component from a raw CycloneDX component dict.

        Args:
            raw: One entry from the CycloneDX ``components`` array.
            sbom_id: The UUID of the parent SBOM.

        Returns:
            A newly created Component domain entity.

        Raises:
            ValueError: If the raw dict is missing required fields or
                the PURL is malformed.
        """
        purl_str = raw.get("purl", "")
        if not purl_str:
            # Components without a PURL use a synthetic placeholder.
            # The binding_status is MISSING because they cannot be matched.
            purl_str = f"pkg:generic/{raw.get('name', 'unknown')}@unknown"
            binding_status = BindingStatus.MISSING
        else:
            binding_status = BindingStatus.AMBIGUOUS  # will be resolved later

        return cls(
            component_id=uuid.uuid4(),
            sbom_id=sbom_id,
            purl=Purl(value=purl_str[:2048]),
            name=raw.get("name", ""),
            version=raw.get("version", ""),
            component_type=raw.get("type", "library"),
            binding_status=binding_status,
            binding_confidence=0.0,
            created_at=datetime.now(tz=UTC),
        )


@dataclass
class Sbom:
    """SBOM domain entity representing an ingested CycloneDX document.

    This is the central aggregate root of the SBOM service. It encapsulates:
    - The CycloneDX document and its digest
    - Verification status of the cosign/Sigstore signature
    - PURL component list derived from the document
    - Provenance metadata (source, timestamps, tenant)

    Attributes:
        sbom_id: Immutable UUID assigned at ingestion time.
        tenant_id: Logical isolation key for multi-namespace evaluation.
        image_digest: Digest of the associated container image.
        sbom_digest: Canonical sha256 digest of the CycloneDX document.
        cyclonedx_document: The full parsed CycloneDX JSON document.
        spec_version: CycloneDX specification version (e.g. ``"1.5"``).
        source: Provenance of the SBOM (syft or external).
        artifact_uri: URI where the SBOM artifact is stored.
        signature_bundle_uri: URI of the cosign signature bundle; required
            for external SBOMs.
        verification_status: Current cosign verification state.
        signing_identity: Verified Fulcio signing identity; None if pending.
        issuer: Verified OIDC issuer URI; None if pending.
        rekor_entry_uuid: Rekor transparency log UUID; None if absent.
        verification_error: Human-readable error message on failure.
        verified_at: UTC timestamp of successful verification; None otherwise.
        generated_at: UTC timestamp when the SBOM was originally generated.
        created_at: UTC timestamp when this record was created by PHANTOM.
        purl_count: Number of resolvable PURLs in the document.
    """

    sbom_id: uuid.UUID
    """Immutable UUID assigned at ingestion time."""

    tenant_id: uuid.UUID
    """Logical isolation key for multi-namespace evaluation."""

    image_digest: ImageDigest
    """Digest of the container image this SBOM describes."""

    sbom_digest: SbomDigest
    """Canonical sha256 digest of the CycloneDX document."""

    cyclonedx_document: dict[str, Any]
    """Full parsed CycloneDX JSON document as stored."""

    spec_version: str
    """CycloneDX specification version string (e.g. '1.5')."""

    source: SbomSource
    """Whether this SBOM came from Syft or an external producer."""

    artifact_uri: str
    """https or s3 URI where the SBOM artifact is stored."""

    signature_bundle_uri: str | None
    """URI of the cosign signature bundle; required when source=external."""

    verification_status: VerificationStatus
    """Current cosign/Sigstore signature verification state."""

    generated_at: datetime
    """UTC timestamp when the SBOM was originally generated by the producer."""

    created_at: datetime
    """UTC timestamp when this record was created by PHANTOM."""

    purl_count: int
    """Number of CycloneDX components that expose a resolvable PURL."""

    signing_identity: str | None = None
    """Verified Fulcio signing identity; None until verification completes."""

    issuer: str | None = None
    """Verified OIDC issuer URI; None until verification completes."""

    rekor_entry_uuid: uuid.UUID | None = None
    """Rekor transparency log entry UUID; None if not recorded."""

    verification_error: str | None = None
    """Human-readable failure reason; None unless verification failed."""

    verified_at: datetime | None = None
    """UTC timestamp of successful verification; None if pending or failed."""

    def __post_init__(self) -> None:
        """Enforce SBOM domain invariants.

        Raises:
            ValueError: If any invariant is violated.
        """
        if not self.spec_version:
            raise ValueError("Sbom.spec_version must not be empty")
        if self.purl_count < 0:
            raise ValueError(
                f"Sbom.purl_count must be >= 0, got {self.purl_count}"
            )
        if self.source == SbomSource.EXTERNAL and not self.signature_bundle_uri:
            raise ValueError(
                "Sbom.signature_bundle_uri is required when source=external"
            )
        if self.created_at.tzinfo is None:
            raise ValueError("Sbom.created_at must be timezone-aware")
        if self.generated_at.tzinfo is None:
            raise ValueError("Sbom.generated_at must be timezone-aware")
        if self.verified_at is not None and self.verified_at.tzinfo is None:
            raise ValueError("Sbom.verified_at must be timezone-aware when set")

    @property
    def component_count(self) -> int:
        """Number of components in the CycloneDX document.

        Returns:
            The length of the ``components`` array, or 0 if absent.
        """
        components = self.cyclonedx_document.get(_CYCLONEDX_COMPONENTS_FIELD, [])
        if not isinstance(components, list):
            return 0
        return len(components)

    def mark_verified(
        self,
        signing_identity: str,
        issuer: str,
        verified_at: datetime,
        rekor_entry_uuid: uuid.UUID | None = None,
    ) -> Sbom:
        """Return a new Sbom with verification status set to VERIFIED.

        This method does not mutate the current instance (immutable update
        pattern preserving auditability).

        Args:
            signing_identity: The Fulcio signing identity that passed verification.
            issuer: The OIDC issuer URI that passed verification.
            verified_at: UTC timestamp of successful verification.
            rekor_entry_uuid: Optional Rekor transparency log entry UUID.

        Returns:
            A new Sbom instance with VERIFIED status and signing metadata.

        Raises:
            ValueError: If verified_at is not timezone-aware.
        """
        if verified_at.tzinfo is None:
            raise ValueError("verified_at must be timezone-aware")
        import dataclasses

        return dataclasses.replace(
            self,
            verification_status=VerificationStatus.VERIFIED,
            signing_identity=signing_identity,
            issuer=issuer,
            verified_at=verified_at,
            rekor_entry_uuid=rekor_entry_uuid,
            verification_error=None,
        )

    def mark_verification_failed(self, reason: str) -> Sbom:
        """Return a new Sbom with verification status set to FAILED.

        Args:
            reason: Human-readable description of why verification failed.

        Returns:
            A new Sbom instance with FAILED status and the failure reason.
        """
        import dataclasses

        return dataclasses.replace(
            self,
            verification_status=VerificationStatus.FAILED,
            verification_error=reason,
            signing_identity=None,
            issuer=None,
            verified_at=None,
        )


@dataclass
class VerificationJob:
    """Domain entity representing an asynchronous cosign verification job.

    Tracks the lifecycle of a single verification attempt for one SBOM.

    Attributes:
        verification_job_id: Immutable UUID for this job.
        sbom_id: UUID of the SBOM being verified.
        tenant_id: Logical isolation key.
        expected_identity: Expected Fulcio signing identity to verify against.
        expected_issuer: Expected OIDC issuer URI.
        rekor_required: Whether a Rekor transparency log entry is mandatory.
        status: Current job lifecycle status.
        submitted_at: UTC timestamp when the job was enqueued.
        completed_at: UTC timestamp when the job finished; None if pending.
        signing_identity: Verified identity if successful; None otherwise.
        issuer: Verified issuer if successful; None otherwise.
        rekor_entry_uuid: Rekor log UUID if found; None otherwise.
        failure_reason: Human-readable failure description; None if not failed.
    """

    verification_job_id: uuid.UUID
    """Immutable UUID for this verification job."""

    sbom_id: uuid.UUID
    """UUID of the SBOM being verified."""

    tenant_id: uuid.UUID
    """Logical isolation key."""

    expected_identity: str
    """Expected Fulcio signing identity; 1..512 characters."""

    expected_issuer: str
    """Expected OIDC issuer URI."""

    rekor_required: bool
    """Whether a Rekor transparency log entry is mandatory."""

    status: str
    """Job status: 'queued', 'running', 'verified', or 'failed'."""

    submitted_at: datetime
    """UTC timestamp when this job was enqueued."""

    completed_at: datetime | None = None
    """UTC timestamp when the job finished; None while still running."""

    signing_identity: str | None = None
    """Verified Fulcio signing identity if successful; None otherwise."""

    issuer: str | None = None
    """Verified OIDC issuer URI if successful; None otherwise."""

    rekor_entry_uuid: uuid.UUID | None = None
    """Rekor transparency log entry UUID if found; None otherwise."""

    failure_reason: str | None = None
    """Human-readable failure description; None if not failed."""

    def __post_init__(self) -> None:
        """Enforce VerificationJob invariants.

        Raises:
            ValueError: If expected_identity is empty, exceeds 512 chars,
                expected_issuer is empty, or status is not a valid value.
        """
        _valid_statuses = {"queued", "running", "verified", "failed"}
        if self.status not in _valid_statuses:
            raise ValueError(
                f"VerificationJob.status must be one of {_valid_statuses}, "
                f"got {self.status!r}"
            )
        if not self.expected_identity or len(self.expected_identity) > 512:
            raise ValueError(
                "VerificationJob.expected_identity must be 1..512 characters"
            )
        if not self.expected_issuer:
            raise ValueError("VerificationJob.expected_issuer must not be empty")
        if self.submitted_at.tzinfo is None:
            raise ValueError("VerificationJob.submitted_at must be timezone-aware")


def validate_cyclonedx_document(document: dict[str, Any]) -> None:
    """Validate that a dict is a minimally valid CycloneDX JSON document.

    Checks only structural invariants that can be validated without the
    full CycloneDX JSON Schema validator (which is an infrastructure concern).

    Args:
        document: The parsed CycloneDX document to validate.

    Raises:
        ValueError: If the document is empty or missing the ``bomFormat``
            field, or if the ``bomFormat`` is not ``"CycloneDX"``.
    """
    if not document:
        raise ValueError("CycloneDX document must not be empty")
    bom_format = document.get(_CYCLONEDX_FORMAT_FIELD)
    if bom_format is None:
        raise ValueError(
            f"CycloneDX document must contain the '{_CYCLONEDX_FORMAT_FIELD}' field"
        )
    if bom_format != "CycloneDX":
        raise ValueError(
            f"CycloneDX document bomFormat must be 'CycloneDX', got {bom_format!r}"
        )


def extract_spec_version(document: dict[str, Any]) -> str:
    """Extract the CycloneDX specVersion field from a parsed document.

    Args:
        document: The parsed CycloneDX document.

    Returns:
        The specVersion string, or ``"unknown"`` if the field is absent.
    """
    return str(document.get("specVersion", "unknown"))


def count_purls_in_document(document: dict[str, Any]) -> int:
    """Count the number of CycloneDX components that expose a non-empty PURL.

    Args:
        document: The parsed CycloneDX document.

    Returns:
        The count of components with a non-empty ``purl`` field; >= 0.
    """
    components = document.get(_CYCLONEDX_COMPONENTS_FIELD, [])
    if not isinstance(components, list):
        return 0
    return sum(1 for c in components if isinstance(c, dict) and c.get("purl"))
