"""
phantom_core.models.sbom — Pydantic models for SBOM API contracts (B.2).

Covers:
- SbomIngestRequest: POST /api/v1/sboms
- SbomRecord: response record embedded in ingest and detail responses
- SbomDetailResponse: GET /api/v1/sboms/{sbom_id}
- SbomVerificationRequest: POST /api/v1/sboms/{sbom_id}/verification
- VerificationJobResponse: response to POST verification
- SbomVerificationResponse: GET /api/v1/sboms/{sbom_id}/verification
"""

from __future__ import annotations

import re
import uuid
from datetime import datetime
from typing import Any, Literal

from pydantic import AnyUrl, Field, field_validator, model_validator

from phantom_core.constants import (
    DIGEST_PATTERN,
    SBOM_ARTIFACT_URI_SCHEMES,
    SCHEMA_VERSION,
)
from phantom_core.models.common import _PhantomBaseModel


def _validate_digest(value: str) -> str:
    """Validate that a string matches the sha256:<64 hex chars> digest format.

    Args:
        value: The digest string to validate.

    Returns:
        The validated digest string, unchanged.

    Raises:
        ValueError: If the value does not match the digest pattern.
    """
    if not re.fullmatch(DIGEST_PATTERN, value):
        raise ValueError(
            f"Digest must match {DIGEST_PATTERN!r}, got {value!r}"
        )
    return value


def _validate_uri_scheme(value: AnyUrl) -> AnyUrl:
    """Validate that a URI uses only https or s3 scheme.

    Args:
        value: The AnyUrl value to validate.

    Returns:
        The validated AnyUrl, unchanged.

    Raises:
        ValueError: If the scheme is not https or s3.
    """
    scheme = str(value).split("://")[0].lower() if "://" in str(value) else ""
    if scheme not in SBOM_ARTIFACT_URI_SCHEMES:
        raise ValueError(
            f"URI scheme must be one of {SBOM_ARTIFACT_URI_SCHEMES}, got {scheme!r}"
        )
    return value


# ---------------------------------------------------------------------------
# POST /api/v1/sboms
# ---------------------------------------------------------------------------


class SbomIngestRequest(_PhantomBaseModel):
    """Request body for ``POST /api/v1/sboms``.

    Attributes:
        schema_version: Always ``"v1"``.
        image_digest: sha256 digest of the associated container image.
        artifact_uri: https or s3 URI pointing to the SBOM artifact.
        cyclonedx_document: Non-empty CycloneDX JSON document.
        declared_sbom_digest: sha256 digest of the CycloneDX document.
        source: Whether the SBOM was generated by Syft or submitted externally.
        generated_at: UTC timestamp when the SBOM was generated.
        signature_bundle_uri: Required when ``source="external"``; https or s3 only.
        tenant_id: Logical isolation key for multi-namespace evaluation.
    """

    schema_version: Literal["v1"] = SCHEMA_VERSION  # type: ignore[assignment]
    image_digest: str
    artifact_uri: AnyUrl
    cyclonedx_document: dict[str, Any] = Field(..., min_length=1)
    declared_sbom_digest: str
    source: Literal["syft", "external"]
    generated_at: datetime
    signature_bundle_uri: AnyUrl | None = None
    tenant_id: uuid.UUID

    @field_validator("image_digest", "declared_sbom_digest", mode="after")
    @classmethod
    def _check_digest(cls, v: str) -> str:
        """Validate digest fields match sha256:<64 hex> format.

        Args:
            v: The digest string.

        Returns:
            The validated digest string.
        """
        return _validate_digest(v)

    @field_validator("artifact_uri", "signature_bundle_uri", mode="after")
    @classmethod
    def _check_uri_scheme(cls, v: AnyUrl | None) -> AnyUrl | None:
        """Validate URI scheme is https or s3.

        Args:
            v: The URI value.

        Returns:
            The validated URI.
        """
        if v is None:
            return v
        return _validate_uri_scheme(v)

    @model_validator(mode="after")
    def _require_signature_for_external(self) -> SbomIngestRequest:
        """Require signature_bundle_uri when source is external.

        Returns:
            The validated model instance.

        Raises:
            ValueError: If source is external but signature_bundle_uri is absent.
        """
        if self.source == "external" and self.signature_bundle_uri is None:
            raise ValueError(
                "signature_bundle_uri is required when source='external'"
            )
        return self


class SbomRecord(_PhantomBaseModel):
    """SBOM record returned from ingest and embedded in detail responses.

    Attributes:
        sbom_id: Immutable UUID assigned at ingest time.
        image_digest: sha256 digest of the associated container image.
        sbom_digest: sha256 digest of the CycloneDX document as stored.
        format: Always ``"CycloneDX"``.
        spec_version: CycloneDX specification version string (e.g. ``"1.5"``).
        component_count: Number of components in the SBOM; non-negative.
        verification_status: Current cosign verification state.
        created_at: UTC timestamp when this record was created.
    """

    sbom_id: uuid.UUID
    image_digest: str
    sbom_digest: str
    format: Literal["CycloneDX"]
    spec_version: str = Field(..., min_length=1)
    component_count: int = Field(..., ge=0)
    verification_status: Literal["pending", "verified", "failed"]
    created_at: datetime


class SbomDetailResponse(_PhantomBaseModel):
    """Response body for ``GET /api/v1/sboms/{sbom_id}``.

    Attributes:
        record: Embedded SbomRecord.
        cyclonedx_document: The full CycloneDX JSON document as stored.
        purl_count: Number of PURLs resolved from this SBOM; non-negative.
        signature_bundle_uri: URI of the cosign signature bundle if present.
        verified_at: UTC timestamp when verification completed; None if pending.
        verification_error: Error message if verification failed; None otherwise.
    """

    record: SbomRecord
    cyclonedx_document: dict[str, Any]
    purl_count: int = Field(..., ge=0)
    signature_bundle_uri: str | None = None
    verified_at: datetime | None = None
    verification_error: str | None = None


# ---------------------------------------------------------------------------
# POST /api/v1/sboms/{sbom_id}/verification
# ---------------------------------------------------------------------------


class SbomVerificationRequest(_PhantomBaseModel):
    """Request body for ``POST /api/v1/sboms/{sbom_id}/verification``.

    Attributes:
        expected_identity: Expected Fulcio/Sigstore signing identity; 1..512 chars.
        expected_issuer: Expected OIDC issuer URI.
        rekor_required: Whether a Rekor transparency log entry is mandatory.
    """

    expected_identity: str = Field(..., min_length=1, max_length=512)
    expected_issuer: AnyUrl
    rekor_required: bool = True


class VerificationJobResponse(_PhantomBaseModel):
    """Response body for ``POST /api/v1/sboms/{sbom_id}/verification``.

    Attributes:
        verification_job_id: UUID identifying this verification job.
        sbom_id: UUID of the SBOM being verified.
        status: Current job status.
        submitted_at: UTC timestamp when the job was enqueued.
    """

    verification_job_id: uuid.UUID
    sbom_id: uuid.UUID
    status: Literal["queued", "running", "verified", "failed"]
    submitted_at: datetime


# ---------------------------------------------------------------------------
# GET /api/v1/sboms/{sbom_id}/verification
# ---------------------------------------------------------------------------


class SbomVerificationResponse(_PhantomBaseModel):
    """Response body for ``GET /api/v1/sboms/{sbom_id}/verification``.

    Attributes:
        verification_job_id: UUID identifying this verification job.
        sbom_id: UUID of the SBOM being verified.
        status: Current or final job status.
        signing_identity: Verified Fulcio identity; None if not yet verified.
        issuer: Verified OIDC issuer; None if not yet verified.
        rekor_entry_uuid: Rekor transparency log entry UUID; None if not recorded.
        verified_at: UTC timestamp of successful verification; None if pending/failed.
        failure_reason: Human-readable failure description; None if not failed.
    """

    verification_job_id: uuid.UUID
    sbom_id: uuid.UUID
    status: Literal["queued", "running", "verified", "failed"]
    signing_identity: str | None = None
    issuer: str | None = None
    rekor_entry_uuid: uuid.UUID | None = None
    verified_at: datetime | None = None
    failure_reason: str | None = None
